name: crazycar
description: "A new Flutter project."

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.7.2




dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  easy_localization: ^3.0.7+1
  cached_network_image: ^3.4.1
  geolocator: ^10.1.1
  flutter_map: ^6.2.1
  latlong2: ^0.9.1




dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^5.0.0



flutter:




  uses-material-design: true


  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Bold.ttf
          weight: 700
  
